name: pytorch
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - matplotlib
  - wandb
  - imageio
  - scikit-image
  - scikit-learn
  - opencv
  - imgaug
  - natsort
  - tqdm
